# Tomcat
server:
  port: 8081

#spring
spring:
  datasource:
    #引用项目中的数据库文件
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/sqlite/home.db
    username:
    password:
  # 指定静态资源的路径
  web:
    resources:
      static-locations: classpath:/static/
